services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - vocaply-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - vocaply-network
    volumes:
      - redis_data:/data

networks:
  vocaply-network:
    driver: bridge

volumes:
  redis_data:
