FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY ../bot-service/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ../bot-service/app ./app
COPY ../shared ./shared

EXPOSE 8001

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001"]
