"""Align schema after model fixes

Revision ID: 411832818d32
Revises: add_performance_indexes
Create Date: 2026-03-06 19:06:18.596120

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '411832818d32'
down_revision = 'add_performance_indexes'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=True),
    sa.Column('calendar_provider', sa.String(length=50), nullable=False),
    sa.Column('external_event_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('all_day', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('has_meeting_url', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('meeting_url', sa.Text(), nullable=True),
    sa.Column('meeting_platform', sa.String(length=50), nullable=True),
    sa.Column('auto_join_enabled', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('auto_join_scheduled', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('auto_join_executed', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('auto_join_scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_event_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('attendees', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('organizer', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('sync_version', sa.Integer(), server_default='1', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'calendar_provider', 'external_event_id', name='uq_calendar_event_external_id')
    )
    op.create_index('idx_cal_events_scheduler', 'calendar_events', ['auto_join_enabled', 'auto_join_scheduled', 'start_time'], unique=False)
    op.create_index('idx_cal_events_user_start', 'calendar_events', ['user_id', 'start_time'], unique=False)
    op.create_index(op.f('ix_calendar_events_company_id'), 'calendar_events', ['company_id'], unique=False)
    op.create_index(op.f('ix_calendar_events_meeting_id'), 'calendar_events', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_calendar_events_start_time'), 'calendar_events', ['start_time'], unique=False)
    op.create_index(op.f('ix_calendar_events_user_id'), 'calendar_events', ['user_id'], unique=False)
    op.drop_index('ix_action_items_assigned_to_id_status', table_name='action_items')
    op.drop_index('ix_action_items_priority_status', table_name='action_items')
    op.drop_index('ix_action_items_status_created_at', table_name='action_items')
    op.drop_index('ix_ai_usage_company_id_created_at', table_name='ai_usage')
    op.alter_column('bot_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('bot_sessions', 'assigned_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('bot_sessions', 'joined_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('bot_sessions', 'left_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('bot_sessions', 'recording_started',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('bot_sessions', 'recording_completed',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('bot_sessions', 'participant_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bot_sessions', 'is_alone',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('bot_sessions', 'alone_since',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('bot_sessions', 'last_heartbeat',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('bot_sessions', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bot_sessions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint('bot_sessions_meeting_id_key', 'bot_sessions', type_='unique')
    op.create_index(op.f('ix_bot_sessions_company_id'), 'bot_sessions', ['company_id'], unique=False)
    op.create_index(op.f('ix_bot_sessions_meeting_id'), 'bot_sessions', ['meeting_id'], unique=True)
    op.drop_constraint('bot_sessions_company_id_fkey', 'bot_sessions', type_='foreignkey')
    op.drop_constraint('bot_sessions_meeting_id_fkey', 'bot_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'bot_sessions', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'bot_sessions', 'meetings', ['meeting_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_meetings_platform_created_at', table_name='meetings')
    op.drop_index('ix_meetings_status_created_at', table_name='meetings')
    op.add_column('platform_connections', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.alter_column('platform_connections', 'token_expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('platform_connections', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('platform_connections', 'last_synced_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('platform_connections', 'connected_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('platform_connections', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('platform_connections_user_id_platform_key', 'platform_connections', type_='unique')
    op.create_index('idx_platform_connections_platform', 'platform_connections', ['platform'], unique=False)
    op.create_index('idx_platform_connections_user_platform', 'platform_connections', ['user_id', 'platform'], unique=True)
    op.create_index(op.f('ix_platform_connections_company_id'), 'platform_connections', ['company_id'], unique=False)
    op.create_index(op.f('ix_platform_connections_user_id'), 'platform_connections', ['user_id'], unique=False)
    op.drop_constraint('platform_connections_company_id_fkey', 'platform_connections', type_='foreignkey')
    op.drop_constraint('platform_connections_user_id_fkey', 'platform_connections', type_='foreignkey')
    op.create_foreign_key(None, 'platform_connections', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'platform_connections', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_transcripts_meeting_id_created_at', table_name='transcripts')
    op.drop_index('ix_transcripts_speaker_id', table_name='transcripts')
    op.drop_index('ix_user_sessions_user_id_created_at', table_name='user_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_sessions_user_id_created_at', 'user_sessions', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_transcripts_speaker_id', 'transcripts', ['speaker_id'], unique=False)
    op.create_index('ix_transcripts_meeting_id_created_at', 'transcripts', ['meeting_id', 'created_at'], unique=False)
    op.drop_constraint(None, 'platform_connections', type_='foreignkey')
    op.drop_constraint(None, 'platform_connections', type_='foreignkey')
    op.create_foreign_key('platform_connections_user_id_fkey', 'platform_connections', 'users', ['user_id'], ['id'])
    op.create_foreign_key('platform_connections_company_id_fkey', 'platform_connections', 'companies', ['company_id'], ['id'])
    op.drop_index(op.f('ix_platform_connections_user_id'), table_name='platform_connections')
    op.drop_index(op.f('ix_platform_connections_company_id'), table_name='platform_connections')
    op.drop_index('idx_platform_connections_user_platform', table_name='platform_connections')
    op.drop_index('idx_platform_connections_platform', table_name='platform_connections')
    op.create_unique_constraint('platform_connections_user_id_platform_key', 'platform_connections', ['user_id', 'platform'])
    op.alter_column('platform_connections', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('platform_connections', 'connected_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('platform_connections', 'last_synced_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('platform_connections', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('platform_connections', 'token_expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('platform_connections', 'created_at')
    op.create_index('ix_meetings_status_created_at', 'meetings', ['status', 'created_at'], unique=False)
    op.create_index('ix_meetings_platform_created_at', 'meetings', ['platform', 'created_at'], unique=False)
    op.drop_constraint(None, 'bot_sessions', type_='foreignkey')
    op.drop_constraint(None, 'bot_sessions', type_='foreignkey')
    op.create_foreign_key('bot_sessions_meeting_id_fkey', 'bot_sessions', 'meetings', ['meeting_id'], ['id'])
    op.create_foreign_key('bot_sessions_company_id_fkey', 'bot_sessions', 'companies', ['company_id'], ['id'])
    op.drop_index(op.f('ix_bot_sessions_meeting_id'), table_name='bot_sessions')
    op.drop_index(op.f('ix_bot_sessions_company_id'), table_name='bot_sessions')
    op.create_unique_constraint('bot_sessions_meeting_id_key', 'bot_sessions', ['meeting_id'])
    op.alter_column('bot_sessions', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('bot_sessions', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bot_sessions', 'last_heartbeat',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('bot_sessions', 'alone_since',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('bot_sessions', 'is_alone',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('bot_sessions', 'participant_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bot_sessions', 'recording_completed',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('bot_sessions', 'recording_started',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('bot_sessions', 'left_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('bot_sessions', 'joined_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('bot_sessions', 'assigned_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('bot_sessions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.create_index('ix_ai_usage_company_id_created_at', 'ai_usage', ['company_id', 'created_at'], unique=False)
    op.create_index('ix_action_items_status_created_at', 'action_items', ['status', 'created_at'], unique=False)
    op.create_index('ix_action_items_priority_status', 'action_items', ['priority', 'status'], unique=False)
    op.create_index('ix_action_items_assigned_to_id_status', 'action_items', ['assigned_to_id', 'status'], unique=False)
    op.drop_index(op.f('ix_calendar_events_user_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_start_time'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_meeting_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_company_id'), table_name='calendar_events')
    op.drop_index('idx_cal_events_user_start', table_name='calendar_events')
    op.drop_index('idx_cal_events_scheduler', table_name='calendar_events')
    op.drop_table('calendar_events')
    # ### end Alembic commands ###
