"""Add user preferences and notification settings

Revision ID: 8eeccf4c1606
Revises: db_optimization_phase1
Create Date: 2026-03-18 20:09:58.472308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8eeccf4c1606'
down_revision = 'db_optimization_phase1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_meeting_attendees_company', table_name='meeting_attendees')
    op.drop_index('idx_meeting_attendees_meeting_email', table_name='meeting_attendees')
    op.drop_index('idx_meeting_attendees_user', table_name='meeting_attendees')
    op.drop_table_comment(
        'meeting_attendees',
        existing_comment='Normalized attendee information for meetings. Replaces JSONB attendees field.',
        schema=None
    )
    op.alter_column('meetings', 'attendees',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='DEPRECATED: Use meeting_attendees table instead',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_index('idx_transcripts_speaker_email', 'transcripts', ['meeting_id', 'speaker_email', 'start_time'], unique=False)
    op.add_column('users', sa.Column('preferences', sa.JSON(), server_default='{"theme": "system", "language": "en", "auto_join_meetings": false}', nullable=False))
    op.add_column('users', sa.Column('notification_settings', sa.JSON(), server_default='{"email_alerts": true, "push_notifications": true, "meeting_reminders": true}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification_settings')
    op.drop_column('users', 'preferences')
    op.drop_index('idx_transcripts_speaker_email', table_name='transcripts')
    op.alter_column('meetings', 'attendees',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='DEPRECATED: Use meeting_attendees table instead',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_table_comment(
        'meeting_attendees',
        'Normalized attendee information for meetings. Replaces JSONB attendees field.',
        existing_comment=None,
        schema=None
    )
    op.create_index('idx_meeting_attendees_user', 'meeting_attendees', ['user_id'], unique=False)
    op.create_index('idx_meeting_attendees_meeting_email', 'meeting_attendees', ['meeting_id', 'email'], unique=True)
    op.create_index('idx_meeting_attendees_company', 'meeting_attendees', ['company_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
