"""Add remaining tables and refine schema

Revision ID: 94d6d2b58c6a
Revises: 6c3b9e69ba47
Create Date: 2026-02-19 21:04:26.703003

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '94d6d2b58c6a'
down_revision = '6c3b9e69ba47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meeting_url', sa.Text(), nullable=True),
    sa.Column('meeting_password', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('platform_meeting_id', sa.String(length=255), nullable=True),
    sa.Column('platform_join_url', sa.Text(), nullable=True),
    sa.Column('platform_start_url', sa.Text(), nullable=True),
    sa.Column('scheduled_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('attendees', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('organizer_email', sa.String(length=255), nullable=True),
    sa.Column('participant_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('recording_url', sa.Text(), nullable=True),
    sa.Column('recording_s3_key', sa.Text(), nullable=True),
    sa.Column('recording_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('recording_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('recording_uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bot_enabled', sa.Boolean(), nullable=False),
    sa.Column('bot_instance_id', sa.String(length=255), nullable=True),
    sa.Column('bot_status', sa.String(length=50), nullable=True),
    sa.Column('bot_joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bot_left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transcript_status', sa.String(length=50), nullable=True),
    sa.Column('transcript_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transcript_word_count', sa.Integer(), nullable=True),
    sa.Column('ai_analysis_status', sa.String(length=50), nullable=True),
    sa.Column('ai_analysis_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action_items_count', sa.Integer(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_meetings_company_created', 'meetings', ['company_id', 'created_at'], unique=False)
    op.create_index('idx_meetings_company_scheduled', 'meetings', ['company_id', 'scheduled_start'], unique=False)
    op.create_index('idx_meetings_company_status', 'meetings', ['company_id', 'status'], unique=False)
    op.create_index('idx_meetings_platform_id', 'meetings', ['platform', 'platform_meeting_id'], unique=False)
    op.create_index(op.f('ix_meetings_company_id'), 'meetings', ['company_id'], unique=False)
    op.create_index(op.f('ix_meetings_created_by'), 'meetings', ['created_by'], unique=False)
    op.create_index(op.f('ix_meetings_platform'), 'meetings', ['platform'], unique=False)
    op.create_index(op.f('ix_meetings_platform_meeting_id'), 'meetings', ['platform_meeting_id'], unique=False)
    op.create_index(op.f('ix_meetings_scheduled_start'), 'meetings', ['scheduled_start'], unique=False)
    op.create_index(op.f('ix_meetings_status'), 'meetings', ['status'], unique=False)
    op.create_table('action_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('assigned_to_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('transcript_quote', sa.Text(), nullable=True),
    sa.Column('transcript_start_time', sa.Float(), nullable=True),
    sa.Column('assignee_name', sa.String(length=255), nullable=True),
    sa.Column('assignee_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_items_assigned_to_id'), 'action_items', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_action_items_assignee_email'), 'action_items', ['assignee_email'], unique=False)
    op.create_index(op.f('ix_action_items_company_id'), 'action_items', ['company_id'], unique=False)
    op.create_index(op.f('ix_action_items_due_date'), 'action_items', ['due_date'], unique=False)
    op.create_index(op.f('ix_action_items_meeting_id'), 'action_items', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_action_items_priority'), 'action_items', ['priority'], unique=False)
    op.create_index(op.f('ix_action_items_status'), 'action_items', ['status'], unique=False)
    op.create_table('meeting_summaries',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('short_summary', sa.String(length=1000), nullable=True),
    sa.Column('detailed_summary', sa.Text(), nullable=True),
    sa.Column('key_points', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('decisions', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('generation_time_seconds', sa.Float(), nullable=True),
    sa.Column('token_usage', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_summaries_company_id'), 'meeting_summaries', ['company_id'], unique=False)
    op.create_index(op.f('ix_meeting_summaries_meeting_id'), 'meeting_summaries', ['meeting_id'], unique=True)
    op.create_table('transcript_metadata',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('total_words', sa.Integer(), nullable=False),
    sa.Column('total_duration_seconds', sa.Float(), nullable=False),
    sa.Column('average_confidence', sa.Float(), nullable=True),
    sa.Column('speaker_count', sa.Integer(), nullable=False),
    sa.Column('speakers', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('detected_language', sa.String(length=10), nullable=True),
    sa.Column('language_confidence', sa.Float(), nullable=True),
    sa.Column('deepgram_request_id', sa.String(length=255), nullable=True),
    sa.Column('processing_time_seconds', sa.Float(), nullable=True),
    sa.Column('deepgram_model', sa.String(length=50), nullable=True),
    sa.Column('audio_duration_billed', sa.Float(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_metadata_company_id'), 'transcript_metadata', ['company_id'], unique=False)
    op.create_index(op.f('ix_transcript_metadata_meeting_id'), 'transcript_metadata', ['meeting_id'], unique=True)
    op.create_table('transcripts',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('speaker_id', sa.String(length=100), nullable=True),
    sa.Column('speaker_name', sa.String(length=255), nullable=True),
    sa.Column('speaker_email', sa.String(length=255), nullable=True),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('channel', sa.Integer(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('words', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('edited_by', sa.String(), nullable=True),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transcripts_meeting_seq', 'transcripts', ['meeting_id', 'sequence_number'], unique=False)
    op.create_index('idx_transcripts_search', 'transcripts', [sa.text("to_tsvector('english', text)")], unique=False, postgresql_using='gin')
    op.create_index('idx_transcripts_speaker', 'transcripts', ['meeting_id', 'speaker_id'], unique=False)
    op.create_index('idx_transcripts_time', 'transcripts', ['meeting_id', 'start_time'], unique=False)
    op.create_index(op.f('ix_transcripts_company_id'), 'transcripts', ['company_id'], unique=False)
    op.create_index(op.f('ix_transcripts_meeting_id'), 'transcripts', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_transcripts_speaker_email'), 'transcripts', ['speaker_email'], unique=False)
    op.create_index(op.f('ix_transcripts_user_id'), 'transcripts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcripts_user_id'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_speaker_email'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_meeting_id'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_company_id'), table_name='transcripts')
    op.drop_index('idx_transcripts_time', table_name='transcripts')
    op.drop_index('idx_transcripts_speaker', table_name='transcripts')
    op.drop_index('idx_transcripts_search', table_name='transcripts', postgresql_using='gin')
    op.drop_index('idx_transcripts_meeting_seq', table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_transcript_metadata_meeting_id'), table_name='transcript_metadata')
    op.drop_index(op.f('ix_transcript_metadata_company_id'), table_name='transcript_metadata')
    op.drop_table('transcript_metadata')
    op.drop_index(op.f('ix_meeting_summaries_meeting_id'), table_name='meeting_summaries')
    op.drop_index(op.f('ix_meeting_summaries_company_id'), table_name='meeting_summaries')
    op.drop_table('meeting_summaries')
    op.drop_index(op.f('ix_action_items_status'), table_name='action_items')
    op.drop_index(op.f('ix_action_items_priority'), table_name='action_items')
    op.drop_index(op.f('ix_action_items_meeting_id'), table_name='action_items')
    op.drop_index(op.f('ix_action_items_due_date'), table_name='action_items')
    op.drop_index(op.f('ix_action_items_company_id'), table_name='action_items')
    op.drop_index(op.f('ix_action_items_assignee_email'), table_name='action_items')
    op.drop_index(op.f('ix_action_items_assigned_to_id'), table_name='action_items')
    op.drop_table('action_items')
    op.drop_index(op.f('ix_meetings_status'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_scheduled_start'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_platform_meeting_id'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_platform'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_created_by'), table_name='meetings')
    op.drop_index(op.f('ix_meetings_company_id'), table_name='meetings')
    op.drop_index('idx_meetings_platform_id', table_name='meetings')
    op.drop_index('idx_meetings_company_status', table_name='meetings')
    op.drop_index('idx_meetings_company_scheduled', table_name='meetings')
    op.drop_index('idx_meetings_company_created', table_name='meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ###
