"""Add bot_sessions table

Revision ID: a3344e86605e
Revises: a1b2c3d4e5f6
Create Date: 2026-02-26 23:50:44.420271

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a3344e86605e'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('bot_instance_id', sa.String(length=100), nullable=True),
    sa.Column('bot_platform', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('recording_started', sa.DateTime(), nullable=True),
    sa.Column('recording_completed', sa.DateTime(), nullable=True),
    sa.Column('recording_url', sa.String(length=500), nullable=True),
    sa.Column('recording_duration', sa.Float(), nullable=True),
    sa.Column('participant_count', sa.Integer(), nullable=True),
    sa.Column('is_alone', sa.Boolean(), nullable=True),
    sa.Column('alone_since', sa.DateTime(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('bot_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id')
    )
    op.create_index('idx_bot_sessions_company', 'bot_sessions', ['company_id', 'status'], unique=False)
    op.create_index('idx_bot_sessions_status', 'bot_sessions', ['status'], unique=False)
    
    op.alter_column('ai_usage', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_usage', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_ai_usage_user_id'), 'ai_usage', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_usage_user_id'), table_name='ai_usage')
    op.alter_column('ai_usage', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_usage', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_bot_sessions_status', table_name='bot_sessions')
    op.drop_index('idx_bot_sessions_company', table_name='bot_sessions')
    op.drop_table('bot_sessions')
    # ### end Alembic commands ###
